In [4]:
import open3d as o3d
# absolute path is: 
pcd = o3d.io.read_point_cloud("scans.pcd")
o3d.visualization.draw_geometries([pcd])


ImportError: DLL load failed while importing pybind: Le module spécifié est introuvable.

In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

image= cv.imread("./images/1732876035469011765.png")

In [9]:
# as a numpy array
image = np.array(image)
#take a look at the mean of each row
#print(image.mean(axis=0))
#only the first 50 rows
#print(image[:50].mean(axis=0))
#the last 50 rows
np.set_printoptions(threshold=np.inf)

print(image[-50:].mean(axis=0))

[[37.08 46.   53.42]
 [37.08 46.   53.42]
 [37.08 46.32 52.44]
 [36.94 46.   53.66]
 [37.42 45.94 54.76]
 [37.8  46.36 54.96]
 [37.58 46.98 55.1 ]
 [37.34 47.12 55.2 ]
 [37.94 47.24 55.24]
 [38.56 47.16 54.82]
 [37.6  46.94 54.32]
 [36.48 46.32 54.32]
 [36.76 45.74 54.18]
 [37.04 46.22 53.86]
 [37.68 46.16 53.54]
 [38.22 46.08 54.44]
 [38.12 46.46 55.06]
 [38.   47.76 54.86]
 [37.94 48.22 54.5 ]
 [37.58 47.42 55.38]
 [38.   47.66 56.16]
 [38.26 47.14 55.76]
 [37.68 46.7  55.26]
 [37.04 46.86 56.58]
 [38.48 47.32 57.64]
 [39.76 48.36 57.24]
 [39.48 49.06 56.82]
 [38.92 49.28 56.38]
 [39.   48.34 55.82]
 [39.08 48.06 55.8 ]
 [38.8  47.74 55.54]
 [38.38 47.74 55.86]
 [38.02 48.22 55.96]
 [37.54 48.26 56.62]
 [38.34 48.3  57.1 ]
 [39.1  48.52 55.74]
 [38.02 48.3  54.14]
 [36.84 47.8  55.24]
 [37.94 47.46 56.26]
 [38.9  47.82 56.74]
 [39.08 48.3  57.  ]
 [39.28 47.68 56.44]
 [38.7  47.36 55.74]
 [38.12 48.22 56.94]
 [38.96 48.58 58.14]
 [39.8  48.72 58.14]
 [39.8  48.72 58.  ]
 [39.56 48.64